#!/usr/bin/env node
// Skanuje public/emotes/{1,2,3} i generuje src/data/emotes.ts.
// Trigger: dir 1 → <name>, dir 2 → <name2>, dir 3 → <name3>.
// `sb/` jest świadomie pomijane.
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath sobie radzi z windowsowym `/C:/...` w URL.pathname; samo
// `.pathname` daje na Windowsie ścieżkę z leading slash, którą path.join
// potem sklejał w `D:\D:\a\...`.
const ROOT = fileURLToPath(new URL("..", import.meta.url));
const EMOTES_DIR = join(ROOT, "public", "emotes");
const OUT = join(ROOT, "src", "data", "emotes.ts");

const DIRS = ["1", "2", "3"];

/** trigger (np. "haha", "haha2") → ścieżka względem /emotes/ (np. "1/haha.gif") */
const map = {};
/** kategoria → posortowane triggery do pickera */
const byCategory = { 1: [], 2: [], 3: [] };

for (const dir of DIRS) {
  const path = join(EMOTES_DIR, dir);
  let entries;
  try {
    entries = readdirSync(path);
  } catch {
    console.warn(`brak ${path}, pomijam`);
    continue;
  }
  const gifs = entries.filter((f) => f.endsWith(".gif")).sort();
  for (const f of gifs) {
    const name = f.replace(/\.gif$/, "");
    const trigger = dir === "1" ? name : `${name}${dir}`;
    if (map[trigger]) {
      console.warn(
        `kolizja triggera "${trigger}": ${map[trigger]} vs ${dir}/${f}, zostawiam pierwszy`,
      );
      continue;
    }
    map[trigger] = `${dir}/${f}`;
    byCategory[dir].push(trigger);
  }
}

// Stabilny output: alfabetycznie po triggerze.
const sortedKeys = Object.keys(map).sort();
const sortedMap = {};
for (const k of sortedKeys) sortedMap[k] = map[k];

const totalCount = sortedKeys.length;
const counts = Object.fromEntries(
  Object.entries(byCategory).map(([k, v]) => [k, v.length]),
);

const out = `// AUTO-GENERATED by scripts/build-emotes.mjs. Nie edytuj ręcznie.
// Triggery:
//   dir 1 → <name>
//   dir 2 → <name2>
//   dir 3 → <name3>
//
// Suma: ${totalCount} emotek (cz1=${counts["1"]}, cz2=${counts["2"]}, cz3=${counts["3"]}).

/** trigger → ścieżka względem /emotes/, np. "1/haha.gif". */
export const EMOTES: Readonly<Record<string, string>> = ${JSON.stringify(sortedMap, null, 2)} as const;

/** Lista triggerów per kategoria (do pickera). */
export const EMOTES_BY_CATEGORY: Readonly<Record<"1" | "2" | "3", readonly string[]>> = {
  "1": ${JSON.stringify(byCategory["1"])},
  "2": ${JSON.stringify(byCategory["2"])},
  "3": ${JSON.stringify(byCategory["3"])},
} as const;
`;

writeFileSync(OUT, out, "utf8");
console.log(`OK: ${OUT}, ${totalCount} emotek`);
